### ISSUE TITLE
关于此项目原创性的质疑？

### ISSUE THREAD

**Issue by yflgda4310** [qishenonly/flydb#20]
此项目不是roseduan的吗，怎么成为你个人的开源项目了？

**Comment by qishenonly** [comment]
首先，此项目灵感来源于国外的数据库开源书籍及roseduan的项目。大部分设计思想及其设计模式来源于开源书籍Build Your Own Database From Scratch 及 Build Your Own Redis With C/C++。项目部分可能与roseduan的项目有部分重合，是因为钻研过rosedb及lotusdb以及跟着roseduan，acild学习过go实战的部分写法。项目开源前已与roseduan严谨商讨过，予以同意，并不影响他的部分利益。
其次，基于bitcask的kv数据库的设计模式大多相同，如果你不信于此，可以去尝试阅读Build Your Own Database From Scratch的前五章，有详细说过kv存储的各种设计。
最后，项目部分重合只是为了快速搭建一个基座，后续会有各种新的创新，感谢您的意见，可以持续关注我们项目的后续开发。
