### ISSUE TITLE
合并过程，内存索引如何更新

### ISSUE THREAD

**Issue by lightnine** [qishenonly/flydb#54]
请教个楼主个问题
1. bitcask中合并文件过程，是将所有旧的数据文件进行合并。然后会创建一个hintfile

合并完成后，内存中的索引哈希表必须要更新，因为这些数据所在的文件已经改变了。请问这个具体的更新过程是怎么样的呢？

**Comment by qishenonly** [comment]
非常感谢您的问题。
首先bitcask论文中并没有提及到合并文件，他是当一个活跃数据文件写满后将其转换为旧数据文件，此文件仅可读。lsm倒是有合并文件的过程，由于bitcask是lsm的简化版，他舍去了这一部分。
其次，创建hintfile是在merge过程中，在论文中，merge过程是为了清理磁盘上无效的数据，防止由于无效数据导致内存极具膨胀。merge过程中会新生成一个临时目录，并启动一个新的db实例从而不影响主进程的正常工作，merge会将无效数据清除，有效数据重写，而新的有效数据的索引和对应的key会存到hintfile中。merge完成后，会将新数据目录里面的数据文件拷贝到原数据目录，替换原有的数据文件，那么hintfile里面的索引对应的就是merge之后的有效数据，再次启动db实例时就会从hintfile里面读取索引。
非常感谢您的提问，希望对您有所帮助。
