### ISSUE TITLE
Mkdir permission denied!

### ISSUE THREAD

**Issue by CrazyJius** [qishenonly/flydb#8]
When I was functional testing flydb's merge code, I found a file read/write bug. When I was building and writing data to the database instance and finally performing the merge operation, I was prompted with an error message indicating insufficient permissions to create.

After some debugging, it is found that the problem is in the getMergePath function of the merge file. The lack of the basic directory of the database results in an error. Hope to fix it as soon as possible.

The bugs are as follows:
![uTools_1683449969184](https://user-images.githubusercontent.com/132639639/236668236-08b2d8da-d59c-4529-9885-69da070d733b.png)

**Comment by qishenonly** [comment]
Thank you for raising the issue, which belongs to my neglect of details in development. Thank you very much for your contribution to our team.
